# Generated by Codex on 2026-05-11

import shutil
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def seed_company_logo(apps, schema_editor):
    source = Path(settings.BASE_DIR) / "logo.webp"
    if not source.exists():
        return

    logo_dir = Path(settings.MEDIA_ROOT) / "branding"
    logo_dir.mkdir(parents=True, exist_ok=True)
    target = logo_dir / "logo.webp"
    if not target.exists():
        shutil.copyfile(source, target)

    SiteBranding = apps.get_model("dashboard", "SiteBranding")
    SiteBranding.objects.update_or_create(pk=1, defaults={"company_logo": "branding/logo.webp"})


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_logo", models.FileField(blank=True, upload_to="branding/", verbose_name="Логотип компании")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
            ],
            options={
                "verbose_name": "Логотип компании",
                "verbose_name_plural": "Логотип компании",
            },
        ),
        migrations.RunPython(seed_company_logo, migrations.RunPython.noop),
    ]
