from django.urls import path

from . import views

urlpatterns = [
    path("", views.request_list, name="request_list"),
    path("calendar/", views.request_calendar, name="request_calendar"),
    path("clients/", views.client_list, name="client_list"),
    path("clients/new/", views.client_create, name="client_create"),
    path("clients/<int:pk>/edit/", views.client_edit, name="client_edit"),
    path("clients/<int:pk>/delete/", views.client_delete, name="client_delete"),
    path("suppliers/", views.supplier_list, name="supplier_list"),
    path("suppliers/new/", views.supplier_create, name="supplier_create"),
    path("suppliers/<int:pk>/edit/", views.supplier_edit, name="supplier_edit"),
    path("suppliers/<int:pk>/delete/", views.supplier_delete, name="supplier_delete"),
    path("requests/new/", views.request_create, name="request_create"),
    path("requests/new-from-pdf/", views.request_create_from_pdf, name="request_create_from_pdf"),
    path("requests/<int:pk>/", views.request_detail, name="request_detail"),
    path("requests/<int:pk>/edit/", views.request_edit, name="request_edit"),
    path("requests/<int:pk>/delete/", views.request_delete, name="request_delete"),
    path("vehicles/", views.vehicle_list, name="vehicle_list"),
    path("vehicles/<int:pk>/edit/", views.vehicle_edit, name="vehicle_edit"),
    path("vehicles/<int:pk>/toggle/", views.vehicle_toggle_active, name="vehicle_toggle_active"),
    path("drivers/", views.driver_list, name="driver_list"),
    path("drivers/<int:pk>/edit/", views.driver_edit, name="driver_edit"),
    path("drivers/<int:pk>/toggle/", views.driver_toggle_active, name="driver_toggle_active"),
    path("panel/", views.admin_panel, name="admin_panel"),
    path("requests/<int:pk>/cargo/add/", views.cargo_item_add, name="cargo_item_add"),
    path("requests/<int:pk>/cargo/<int:item_pk>/toggle/", views.cargo_item_toggle, name="cargo_item_toggle"),
    path("requests/<int:pk>/cargo/<int:item_pk>/toggle-cz/", views.cargo_item_toggle_cz, name="cargo_item_toggle_cz"),
    path("requests/<int:pk>/cargo/<int:item_pk>/supply-date/", views.cargo_item_supply_date, name="cargo_item_supply_date"),
    path("requests/<int:pk>/cargo/<int:item_pk>/delete/", views.cargo_item_delete, name="cargo_item_delete"),
    path("requests/<int:pk>/cargo/<int:item_pk>/toggle-stocked/", views.cargo_item_toggle_stocked, name="cargo_item_toggle_stocked"),
    path("requests/<int:req_pk>/cargo/<int:item_pk>/pickup/create/", views.supply_pickup_create_for_item, name="supply_pickup_create_for_item"),
    path("pickups/", views.supply_pickup_list, name="supply_pickup_list"),
    path("pickups/new/", views.supply_pickup_create, name="supply_pickup_create"),
    path("pickups/<int:pk>/", views.supply_pickup_detail, name="supply_pickup_detail"),
    path("pickups/<int:pk>/update-date/", views.supply_pickup_update_date, name="supply_pickup_update_date"),
]
