# Generated by Django 5.2.14 on 2026-05-07 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('supply', 'Снабжение'), ('transport', 'Транспорт'), ('warehouse', 'Склад'), ('driver', 'Водитель'), ('manager', 'Руководитель')], max_length=32, unique=True, verbose_name='Код'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('supply', 'Снабжение'), ('transport', 'Транспорт'), ('warehouse', 'Склад'), ('driver', 'Водитель'), ('manager', 'Руководитель')], max_length=32, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('telegram_id', models.CharField(blank=True, max_length=64, verbose_name='Telegram ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
