# Generated by Django 5.2.14 on 2026-05-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_code_userprofile'),
        ('transport', '0002_update_vehicle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profiles', to='transport.vehicle', verbose_name='Автомобиль по умолчанию'),
        ),
    ]
