# Generated by Django 5.2.14 on 2026-05-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_default_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('driver', 'Водитель'), ('manager', 'Руководитель')], max_length=32, verbose_name='Роль'),
        ),
    ]
