# Generated by Django 5.2.14 on 2026-05-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('supply', 'Снабжение'), ('transport', 'Транспорт'), ('warehouse', 'Склад'), ('driver', 'Водитель'), ('manager', 'Руководитель')], max_length=32, verbose_name='Роль'),
        ),
    ]
