# Generated by Django 6.0.5 on 2026-05-10 14:10

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_status_filters',
            field=models.JSONField(blank=True, default=apps.accounts.models.default_calendar_status_filters, verbose_name='Фильтры статусов календаря'),
        ),
    ]
