# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile_calendar_status_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="request_list_period",
            field=models.CharField(
                choices=[
                    ("day", "День"),
                    ("week", "Рабочая неделя"),
                    ("two_weeks", "2 недели"),
                    ("month", "Месяц"),
                ],
                default="month",
                max_length=16,
                verbose_name="Период списка заявок",
            ),
        ),
    ]
