# Generated by Django 5.2.14 on 2026-05-07 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('region', models.CharField(max_length=120, verbose_name='Регион')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='Контакт')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название')),
                ('region', models.CharField(max_length=120, verbose_name='Регион')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер заявки')),
                ('region', models.CharField(max_length=120, verbose_name='Регион доставки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('waiting_supply', 'Ожидает снабжение'), ('waiting_arrival', 'Ожидает поступление'), ('in_warehouse', 'На складе'), ('cz_check', 'Проверка ЦЗ'), ('ready_to_ship', 'Готова к отгрузке'), ('transport_assigned', 'Назначен транспорт'), ('shipped', 'Отгружена'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('problem', 'Проблема'), ('closed', 'Закрыта')], db_index=True, default='created', max_length=32, verbose_name='Статус')),
                ('cargo_name', models.CharField(max_length=180, verbose_name='Груз')),
                ('cargo_weight_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес, кг')),
                ('requested_delivery_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата доставки')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='transport.driver', verbose_name='Водитель')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='transport.vehicle', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='logistics.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='logistics.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Логистическая заявка',
                'verbose_name_plural': 'Логистические заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('created', 'Создана'), ('waiting_supply', 'Ожидает снабжение'), ('waiting_arrival', 'Ожидает поступление'), ('in_warehouse', 'На складе'), ('cz_check', 'Проверка ЦЗ'), ('ready_to_ship', 'Готова к отгрузке'), ('transport_assigned', 'Назначен транспорт'), ('shipped', 'Отгружена'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('problem', 'Проблема'), ('closed', 'Закрыта')], max_length=32, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('created', 'Создана'), ('waiting_supply', 'Ожидает снабжение'), ('waiting_arrival', 'Ожидает поступление'), ('in_warehouse', 'На складе'), ('cz_check', 'Проверка ЦЗ'), ('ready_to_ship', 'Готова к отгрузке'), ('transport_assigned', 'Назначен транспорт'), ('shipped', 'Отгружена'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('problem', 'Проблема'), ('closed', 'Закрыта')], max_length=32, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='logistics.logisticsrequest', verbose_name='Заявка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
