# Generated by Django 5.2.14 on 2026-05-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_expand_logistics_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsrequest',
            name='request_number',
            field=models.CharField(blank=True, default='', max_length=32, unique=True, verbose_name='Номер заявки'),
        ),
    ]
