# Generated by Django 5.2.14 on 2026-05-08 22:55

from django.db import migrations, models


def migrate_priority_values(apps, schema_editor):
    LogisticsRequest = apps.get_model("logistics", "LogisticsRequest")
    LogisticsRequest.objects.filter(priority="low").update(priority="normal")
    LogisticsRequest.objects.filter(priority="high").update(priority="urgent")


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_rename_status_history_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsrequest',
            name='cz_problem',
            field=models.BooleanField(default=False, verbose_name='Проблема Честного Знака'),
        ),
        migrations.RunPython(migrate_priority_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='logisticsrequest',
            name='priority',
            field=models.CharField(choices=[('normal', 'Обычный'), ('urgent', 'Срочный'), ('vip', 'VIP'), ('critical', 'Критический')], default='normal', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='logisticsrequest',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('waiting_supply', 'Ожидает снабжение'), ('waiting_arrival', 'Ожидает поступление'), ('in_warehouse', 'На складе'), ('cz_check', 'Проверка ЦЗ'), ('ready_to_ship', 'Готова к отгрузке'), ('transport_assigned', 'Назначен транспорт'), ('shipped', 'Отгружена'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('problem', 'Проблема'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], db_index=True, default='created', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='new_status',
            field=models.CharField(choices=[('created', 'Создана'), ('waiting_supply', 'Ожидает снабжение'), ('waiting_arrival', 'Ожидает поступление'), ('in_warehouse', 'На складе'), ('cz_check', 'Проверка ЦЗ'), ('ready_to_ship', 'Готова к отгрузке'), ('transport_assigned', 'Назначен транспорт'), ('shipped', 'Отгружена'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('problem', 'Проблема'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], max_length=32, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='requeststatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('created', 'Создана'), ('waiting_supply', 'Ожидает снабжение'), ('waiting_arrival', 'Ожидает поступление'), ('in_warehouse', 'На складе'), ('cz_check', 'Проверка ЦЗ'), ('ready_to_ship', 'Готова к отгрузке'), ('transport_assigned', 'Назначен транспорт'), ('shipped', 'Отгружена'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('problem', 'Проблема'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], max_length=32, verbose_name='Старый статус'),
        ),
    ]
