# Generated by Django 6.0.5 on 2026-05-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_logisticsrequest_cz_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retention_days', models.PositiveIntegerField(default=180, verbose_name='Хранить заявки в работе, дней')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки архивариуса',
                'verbose_name_plural': 'Настройки архивариуса',
            },
        ),
    ]
