# Generated by Django 5.2.14 on 2026-05-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_viewer_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('qty', models.CharField(blank=True, max_length=150, verbose_name='Количество / единица')),
                ('needs_supply', models.BooleanField(default=True, verbose_name='К обеспечению')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='logistics.logisticsrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
