# Generated by Django 5.2.14 on 2026-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_supply_pickup_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsrequest',
            name='cargo_description',
            field=models.TextField(blank=True, default='', verbose_name='Описание груза'),
        ),
    ]
