# Generated by Django 5.2.14 on 2026-05-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_cargo_description_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsrequest',
            name='client_phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Телефон / Email'),
        ),
        migrations.AlterField(
            model_name='logisticsrequest',
            name='client_contact',
            field=models.CharField(blank=True, max_length=160, verbose_name='ФИО контактного лица'),
        ),
    ]
