# Generated by Django 5.2.14 on 2026-05-07 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('delay', 'Задержка'), ('documents', 'Документы'), ('damage', 'Повреждение'), ('route', 'Маршрут'), ('other', 'Другое')], max_length=32, verbose_name='Тип проблемы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='problems/%Y/%m/', verbose_name='Фото')),
                ('resolution_status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Решена')], default='open', max_length=32, verbose_name='Статус решения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_problems', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='logistics.logisticsrequest', verbose_name='Заявка')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problems', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Проблема',
                'verbose_name_plural': 'Проблемы',
                'ordering': ['-created_at'],
            },
        ),
    ]
