# Generated by Django 5.2.14 on 2026-05-08 22:55

from django.db import migrations, models


def migrate_problem_type_values(apps, schema_editor):
    ProblemReport = apps.get_model("problems", "ProblemReport")
    mapping = {
        "delay": "transport_delay",
        "documents": "document_mismatch",
        "damage": "damaged_packaging",
        "route": "transport_delay",
    }
    for old_value, new_value in mapping.items():
        ProblemReport.objects.filter(problem_type=old_value).update(problem_type=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_update_problem_report_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_problem_type_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='problemreport',
            name='problem_type',
            field=models.CharField(choices=[('damaged_packaging', 'Повреждена упаковка'), ('wrong_pallets', 'Неверные паллеты'), ('missing_goods', 'Недостача товара'), ('cz_issue', 'Проблема ЧЗ'), ('client_refused', 'Клиент отказался'), ('partial_acceptance', 'Частичная приёмка'), ('document_mismatch', 'Несоответствие документов'), ('transport_delay', 'Задержка транспорта'), ('other', 'Другое')], max_length=32, verbose_name='Тип проблемы'),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('cancelled', 'Отменена')], default='open', max_length=32, verbose_name='Статус'),
        ),
    ]
