# Generated by Django 6.0.5 on 2026-05-10 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0005_logisticsrequest_cz_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('supply', 'Снабжение'), ('transport', 'Транспорт'), ('warehouse', 'Склад'), ('driver', 'Водитель'), ('manager', 'Руководитель')], max_length=32, verbose_name='Роль получателя')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='logistics.logisticsrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
