# Generated by Django 5.2.14 on 2026-05-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_pickup_request_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор'), ('supply', 'Снабжение'), ('transport', 'Транспорт'), ('warehouse', 'Склад'), ('driver', 'Водитель'), ('manager', 'Руководитель'), ('viewer', 'Наблюдатель')], max_length=32, verbose_name='Роль получателя'),
        ),
    ]
